language: node_js
node_js:
## Some of the ES6 syntax used in the browser-polyfill sources is only supported on nodejs >= 6
## and the selenium-webdriver dependency used by the integration tests requires nodejs >= 8.
- '8'

script:
- npm run build
- npm run test-coverage
- echo "RE-RUN tests on the minified file" && npm run test-minified
- echo "RE-RUN tests on the webpack and browserify bundled files" &&
  npm install -g browserify webpack webpack-cli &&
  ./test/run-module-bundlers-smoketests.sh
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- echo "RUN integration tests on real browsers" &&
  TRAVIS_CI=true ./test/run-browsers-smoketests.sh

## See https://docs.travis-ci.com/user/chrome
sudo: required

addons:
  firefox: 'latest'
  chrome: 'stable'

after_script: npm run publish-coverage

notifications:
  irc:
    channels:
    - irc.mozilla.org#webextensions
    on_success: change
    on_failure: always
    use_notice: true
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (%{build_url})"

deploy:
  provider: npm
  email: addons-dev-automation+npm@mozilla.com
  skip_cleanup: true
  on:
    tags: true
    repo: mozilla/webextension-polyfill
    branch: master
  api_key:
    secure: K4rZPsnERK4hiVJICp2MGjLSiL64AeDc0yxmr54/ZlbAYy5OhtDrtaZ0L65eGx+HuIgVQbduSNn1zBN/Bx7w8zmYVyXdTVD1HqXuopS+vmBTrwW/d28uKdpCcMo311ODbk//AL3ylTCeOMkSsLsbb5Io6zcEpuw0VLtSNSrytaA85vcUIj2l8iurLrThN3r7iIsIEHceCzDo3KDx/o4yh7cEKs0FP9Jl8A6jm8sTt/j3jLmsxFFXp/SWOvPCQFX1hCu2uLgCtoLbFJlaDq2+RzsEXv4K5Ee5coVtc4vLRiNjC1UP7cHqfN8VZ0I2LeVT79MRmLqRAccGCSMdarFgoA2SW1laNch0vXy6hBSluh+OVJVPDrz7Xdyy70rt+57tJYFCtpZ24E6X+GNyOOMYfIsatvv59h5R6vE3hWvNZVtiOhYw9wMrKBA9rLkzyoCXeEVu4BuU834RbeeYUAg9VR6WZ1U2nD4IxGr33mSPDqsA6tOhr7tM0kEmg2eVe8qHop8BRtUAhQfkY6C+kfRkPE0OZBq4kiWcfugRJyKI7rAp9T5JNUSLW5X1KrvRv0RBaDr8SKFaWHE4N5Dbt/u2zluq+wJn/n5IxvEFDHSAzxLWBDz+LsmZ1eXRdfA+Pu4cyIKjMX1O8yPAnX8RCTc9oq8Qj74l5rXzCJtmygRdf2I=
