language: node_js
sudo: false
node_js:
## Some of the ES6 syntax used in the browser-polyfill sources is only supported on nodejs >= 6
- '6'

script:
- npm run build
- npm run test-coverage
- echo "RE-RUN all tests on the minified file" && TEST_MINIFIED_POLYFILL=1 npm run test

after_script: npm run publish-coverage

notifications:
  irc:
    channels:
    - irc.mozilla.org#webextensions
    on_success: change
    on_failure: always
    use_notice: true
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (%{build_url})"
